options:
   auto-update: true

Reactor_Core_Hologram_Particles: 100

uranMax: 12

announceReactorExplosion: true

# announce whose reactor exploded so that everyone can pity them, laugh at them, or both
announceReactorOwner: true

# set if explosions are bigger
# WARNING: This will lag the server when explosion occurs
biggerExplosion: false